### ISSUE TITLE
Q: cloud vs local access

### ISSUE THREAD

**Issue by pergolafabio** [TJForc/risco-lan-bridge#1]
Hi, as discussed earlier in the other thread, ypu reverse engineerd the CS software, so for people with older TCP modules (only 1 socket), its not possible to make use of this project if cloud is enabled

Since you use the CS instructions, can you make it possible to connect to the panel through cloud with this info below, so its only the connection string thats different

![image](https://user-images.githubusercontent.com/43251136/126866901-470b7aad-370e-4c29-a332-a71711c5c1c0.png)

PS: offcourse, this only possible for people who have an risco installer account, this is not possible with normal cloud accounts

Also another question, why do you default disable riscocloud when you run this project?
// Defines if the plugin should deactivate RiscoCloud on the control panel (Optional)
Disable_RiscoCloud:  true,

**Comment by TJForc** [comment]
Technically, it is possible to program a tcp proxy which can be inserted between the central and the cloud and which would allow you to insert commands but unless you have access to the dns on the network, it will not be to my knowledge not possible to create a "transparent" proxy, this will therefore require having control over the configuration of the control panel to indicate the IP address of the proxy, then the proxy will take care of transmitting the frames to RiscoCloud.

Regarding the deactivation of the Cloud at the level of the panel itself, it is not necessary to have an installer account and to use the software "Configuration Software", all the modifications can be made from the keyboard, from where the importance of knowing the installer code to access the configuration (the programming manuals are all downloadable from the internet with the description of the corresponding menus).

Finally, concerning my choice to deactivate the RiscoCloud by default, this comes from two points:
- my code is not intended to be used as is but to serve as an interface/bridge, so this option should either be offered to the end user, or fixed at true or false in the developer's code when he creates the instance to connect to the control panel.
- I consider that Risco, through the RiscoCloud, is able to push a firmware update rendering inoperative my code in whole or in parts; It therefore seems more logical to me from this perspective to deactivate the riscoCloud by default (even if it seems to me very complicated for risco to develop a new algorithm that can be applied to the old as well as to the new central, which in this case would have to be that they also take into account the fact that all of the panels sold are not connected to the cloud, that some are not maintained by "professional" installers which could pose a serious problem if the update goes wrong - that said, I am not sure that a professional will appreciate having to intervene or change equipment because an action by Risco will have crashed an installation but from experience, Risco does not care much - that their software should be compatible with both protocols and that the Local API should very probably also be updated with all the issues that this can also pose on the side of partners who have developed official plugins for their security solution) .

**Comment by pergolafabio** [comment]
ok, interesting, ok, gonna update my TCP module then :-)
i dont think risco is able to push firmware though, only installers do this normally...
i also sometimes prefer to use the risco app, its usefull for push messages when the alarm goes of and watch the video streams

**Comment by robertboccia** [comment]
There was someone who was busy with the local risco solution that onfreund was talking to. I assume this is the same one, essentially onfreund was saying the node package has to be converted to a python package to be used for home assistant,  this would be first prize, the risco app is a joke to be honest and until the existing integration broke a week or so ago I stopped using their app last year already, the integration that was working armed and disarmed far quicker than their own app. If we could get a local integration working that would be amazing. I am running a prosysplus panel and have spent tons on my risco Alarm in excess of 10k usd, but it has to be something that works inside home assistant, since all my automation is inside home assistant, I was polling risco every second as I was using pir sensors to drive light automations.

I am not sure how close the change to a python package is but that according to onfreund would solve our issue.

Robert Boccia

________________________________

**Comment by robertboccia** [comment]
Hi

Are you in touch with onfreund with regards to your local lan development and creating the python package?

**Comment by TJForc** [comment]
Not at the moment and for at least 3 reasons:
- I developed this code to provide an alternative (especially not having to pay Risco) to integrate it into Homebridge at first, I am currently working with @gawindx on this point but several problems arise regarding the design itself classes and circular reference errors have appeared. Therefore, the code is not Ok as is (I would have been surprised otherwise for a first draft). But this will force me to revisit the basic design of the classes.
- Several users are unable to connect to their control panels due to the older generation IP module and the only way to get around this will be to offer the possibility of working with a TCP proxy instead of a direct connection ( in any case to offer this possibility).
- As the code requires several evolutions before being considered as stable and that I have only had very little experience with Python, I will not have fun developing in another language that I do not master as long as the code of base will require such big modifications

Now, if a developer wishes to stick to it, I remain open for explanations on the protocol that I am starting to have well understood.

When the code is in version 1.x.x, it will be time to switch to a port to another language.
As a paliative solution, it seems to me that it is possible to recover HomeKit devices with HA (but I could be wrong), this would allow to wait for the time of the development of the code under Python (of course, once the HomeBridge part will be functional, which should happen fairly quickly).

**Comment by TJForc** [comment]
> Also another question, why do you default disable riscocloud when you run this project?
> // Defines if the plugin should deactivate RiscoCloud on the control panel (Optional)
> Disable_RiscoCloud: true,

@pergolafabio, version 0.9.8 will offer the possibility of reactivating the RiscoCloud, your question made me think about the subject and it seems to me preferable to add an option allowing it if we take into account the fact that all the users will not necessarily have the possibility of reactivating it by themselves otherwise.

@robertboccia, the ongoing integration for Homebridge is well under way from what gawindx told me.
For my part, it remains to integrate the "Proxy" mode, I could then see if it is possible to port the code under Python.

**Comment by robertboccia** [comment]
I'm after integration for home assistant

**Comment by pergolafabio** [comment]
Have you found someone to convert to Python.

**Comment by robertboccia** [comment]
No not yet

**Comment by robertboccia** [comment]
> > Also another question, why do you default disable riscocloud when you run this project?
> > // Defines if the plugin should deactivate RiscoCloud on the control panel (Optional)
> > Disable_RiscoCloud: true,
> 
> @pergolafabio, version 0.9.8 will offer the possibility of reactivating the RiscoCloud, your question made me think about the subject and it seems to me preferable to add an option allowing it if we take into account the fact that all the users will not necessarily have the possibility of reactivating it by themselves otherwise.
> 
> @robertboccia, the ongoing integration for Homebridge is well under way from what gawindx told me.
> For my part, it remains to integrate the "Proxy" mode, I could then see if it is possible to port the code under Python.

I'm not sure if there are any different things for prosys plus which is the panel I have

**Comment by TJForc** [comment]
> I'm not sure if there are any different things for prosys plus which is the panel I have

@robertboccia , I'm not sure I fully understand what you mean.

Theoretically, this code is compatible with all Risco control panels which can be configured via the "Configuration Software".
I took into account the specifications of each type of control panel for the number of zones, outputs, partitions, etc.
I have also taken into account the firmware versions for which the maximum number of zones or outputs have been modified.

For the Prosys, however, I did not take into account the detector above 128, which are unlocked by license.

If you want to validate the functioning of the code with your system, the easiest way would be to test it (under Windows with Visual Studio Code).

You could see if it is compatible or not (And for my part it could allow to validate or correct the operation with a Prosys because for the moment I have not had any feedback except my own installation and that of @gawindx but unfortunately we are both equipped with a LightSys with a recent ip module).

**Comment by robertboccia** [comment]
Message me on robert.boccia@live.co.za let's chat about details there

**Comment by mrbarbz** [comment]
Can someone assist in helping get CS.

**Comment by pergolafabio** [comment]
Do you mean the CS software?

**Comment by mrbarbz** [comment]
> Do you mean the CS software?

Yes please

**Comment by pergolafabio** [comment]
just google it , enough places where you can download it 
example : https://ftp.secplan.de/Anleitungen/RISCO/Software/

**Comment by mrbarbz** [comment]
Is there any special way I need to install it, I keep getting database error.

![Risco](https://user-images.githubusercontent.com/13446996/147915510-5b30740f-6abd-40cc-b77c-ccdd0d27cf68.JPG)
r

**Comment by pergolafabio** [comment]
Yes, there is another tool installer also, system initializer  ,  you first need to create the database

**Comment by mrbarbz** [comment]
> initializer

Database issues fixed thanks

**Comment by mrbarbz** [comment]
I've been searching and trying for weeks before posting my issue. I don't know where to ask either.

I can't seem to connect to my Alarm panel via CS software, both TCP and Cloud. 
Also tried connecting locally via docker image (@vanackej/risco-mqtt-local) but I can never get a connection 

I've forwarded ports 33000 and 34000 on my router, doubled checked the panel ID

The Error Codes I get on CS software are 
20014
![Error20014](https://user-images.githubusercontent.com/13446996/151932986-d919924a-dab4-4b29-af5d-f7c80b8f006c.jpg)


 20016
![Error20016](https://user-images.githubusercontent.com/13446996/151933022-51fe79f7-0d29-4d7b-a81f-fe4dde4e6643.jpg)



Cancelled by user
![ErrorCancelled](https://user-images.githubusercontent.com/13446996/151933061-6037ca1a-0004-43e3-adf2-299f1debbfd0.jpg)




The log in the docker image is "panel is not connected, waiting", "Socket timed out", "TCP socket is disconnected".
![ErrorDocker](https://user-images.githubusercontent.com/13446996/151933287-052412fd-995a-4840-84bb-e5d88612658b.JPG)


Any help will be highly appreciated.

**Comment by pergolafabio** [comment]
first of all, do you have an old board? what firmware? level 2.x ? if yes, then its normal that you cant accss your panel
The TCP module can only allow 1 connection to it

3 options : 
- Disable cloud on your panel, that means you cant use the risco app anymore
- Upgrade your hardware with newer TCP model, that allows multiple connections
- Use the proxy, if you have an advanced router with IPtables, you can forward all OUTGOING connectins to an internal IP, this NOT the same as portforwarding... OR setup your panel to router the traffic to your docker instance instead of wwww.riscocloud.com:33000 , but you need to have admin access


To the screenshots above, if you have the old TCP board , with firmware 2.x , then its normal behaviour you cant connect to your panel, only if you disable cloud access, but you need todo it on a keypad, with the master installer code
Afterwards you can make use of the software

**Comment by mrbarbz** [comment]
How can I tell which board version I have? 

Here is a picture but not sure if that helps. The sticker has V3.91
![RiscoPanelSW](https://user-images.githubusercontent.com/13446996/151952256-6825ae86-d724-458f-8f9a-f2679c1eabc6.jpg)

**Comment by pergolafabio** [comment]
hmm, no idea, never looked at it :-)

can you check if your port is open on the board?  port 1000

**Comment by mrbarbz** [comment]
If the IP module was the old module, shouldn't the Cloud connection on the SC software still work?
I can connect to my panel via the Risco cloud app, browser, and Home Assistant intergration.

Here are some of the settings, hopefully, you can see something I don't see


![Controls](https://user-images.githubusercontent.com/13446996/152039816-880dc0bb-ce2b-470d-b654-e27810ee34c6.jpg)
![listener_port](https://user-images.githubusercontent.com/13446996/152039821-8ed1d46c-b6b0-4b9f-83c4-56ece00f8c9a.JPG)
![IP_port](https://user-images.githubusercontent.com/13446996/152039822-ee87525e-1b3d-4f00-9452-74eead28a82c.JPG)
![Remote ID](https://user-images.githubusercontent.com/13446996/152039828-047d383a-6b4e-424e-92d8-51b8929fa265.jpg)

![CS_Cloud](https://user-images.githubusercontent.com/13446996/152039890-c2e4440e-807b-4e0c-87a3-4229cd679c09.JPG)
![CS_Configuration](https://user-images.githubusercontent.com/13446996/152039893-3421ff2a-aec4-492e-ac08-dad3b071fef1.jpg)

**Comment by pergolafabio** [comment]
The current home Assistant integration also uses the cloud... Check if your port 1000 is open, if it is, then you have the new TCP module, if it's not, you need to disable cloud or use the proxy, see previous reply

**Comment by mrbarbz** [comment]
How can I check if it's open?

**Comment by pergolafabio** [comment]
With nmap for example, just Google enough tools

nmap –p 1000 192.168.0.1

**Comment by mrbarbz** [comment]
Did a scan, Not sure what that means 


![nmap](https://user-images.githubusercontent.com/13446996/152114390-45cc27d0-9dfb-42b0-94e0-2bdf9866e789.jpg)

**Comment by mrbarbz** [comment]
Does that mean installer has blocked it

**Comment by pergolafabio** [comment]
try this project : https://github.com/vanackej/risco-mqtt-local

**Comment by mrbarbz** [comment]
I have tried it, I get socket Socket timed out error.

I also raised an issue vanackej closed it and wasn't resolved

**Comment by mrbarbz** [comment]
https://github.com/vanackej/risco-mqtt-local/issues/13

**Comment by mrbarbz** [comment]
Because I can't connect to cloud via CS software. I'm guessing this is a limitation from the installer.

If I was to factory reset, would that remove the installer and allow me to assign myself as new installer?

**Comment by pergolafabio** [comment]
you dont need a factory reset, just call risco, ask to remove the panel from the installer account, 
then you create an installer account, and attached the panel id to your new account

done!

**Comment by mrbarbz** [comment]
Oh cool.. Easier than factory reset 
Who's or what is dobiss

**Comment by pergolafabio** [comment]
i mean "risco" , type error :-)

**Comment by mrbarbz** [comment]
Oh ok thanks

**Comment by Sylanorr** [comment]
Hi everyone ! 
I'm using this Plugin on Homebridge (The Homebridge Risco Local Platform from Gawindx https://github.com/gawindx/homebridge-risco-local-platform#readme).

I just wanna know if I can use the Proxy method for using both Risco cloud and local connexion with my old Lightsys 2 (single connexion) on Homebridge ?

Thank you

**Comment by pergolafabio** [comment]
> Hi everyone ! I'm using this Plugin on Homebridge (The Homebridge Risco Local Platform from Gawindx https://github.com/gawindx/homebridge-risco-local-platform#readme).
> 
> I just wanna know if I can use the Proxy method for using both Risco cloud and local connexion with my old Lightsys 2 (single connexion) on Homebridge ?
> 
> Thank you

Yes, that's the purpose of the proxy

**Comment by Sylanorr** [comment]
Hello and thank you.

Either I'm doing it really wrong, or it's not possible to make it work.

I use this plugin: https://github.com/gawindx/homebridge-risco-local-platform#readme which has for dependency the Risco-Lan-Bridge of TJForc.

I wonder if the code related to the Proxy has been integrated in the plugin I'm using ... Because I have no reference to it when I consult my logs (and even in debug).

**Please, can someone who has managed to get the Proxy mode working via Homebridge tell me what they did to get it working?** 

FYI, I have an old network card that only accepts one connection on a Lightsys 2 control unit

Here is what I did: 

I changed the cloud IP of my panel to the IP of my raspberry Pi that hosts Homebridge (192.168.0.18) and left the port at 33000.

Here is my config file: 

 {
    "platform": "RiscoLocalAlarm",
    "name": "RiscoLocalAlarm",
    "Panel_IP": "192.168.0.11",
    "Panel_Port": 1000,
    "Panel_Model": "lightsys",
    "Panel_Password": 5678,
    "Panel_Key": 1,
    "AutoDiscover": true,
    "Enable_RiscoCloud": true,
    "SocketMode": "proxy",
    "ListeningPort": 33000,
    "CloudPort": 33000,
    "CloudUrl": "www.riscocloud.com",
    "OccupancyPreventArming": false,
    "Partition": "all",
    "Outputs": "all",
    "Detectors": "none"
}

This works locally, but riscocloud never connects...

Please help
(My mail : sylanor@gmail.com)

**Comment by pergolafabio** [comment]
proxy works for me, allthough using HA , not homebridge, i also have older lightsys :-)

but using this rewritten project : https://github.com/vanackej/risco-mqtt-local

**Comment by Sylanorr** [comment]
I think this may be the problem, the proxy is not implemented on the Gawindx fork.

Maybe I should migrate to HA.
